# configuration file for simtools

useMongoDB: true
mongoDBConfigFile: ./dbDetails.yml

modelFilesLocations: [
  /workdir/external/simulation-model-description/configReports/,
  /workdir/external/simulation-model-description/datFiles/,
  /workdir/external/external/data-from-instrument-teams/
]

outputLocation: /workdir/external/output/

testDataLocation: './data/'

simtelPath: /workdir/sim_telarray/

# Not used yet
submissionCommand: 'qsub '
