---
name: CI-integrationtests
# Execute integration tests for docker container
# with gammasim-tools
env:
  DB_SERVER: ${{ secrets.DB_SERVER }}
  DB_API_USER: ${{ secrets.DB_API_USER }}
  DB_API_PW: ${{ secrets.DB_API_PW }}
  DB_API_PORT: ${{ secrets.DB_API_PORT }}

on:
  push:
    tags:
      - 'v*'
  pull_request:
    branches: ["main"]
  release:
    types: [published]

jobs:

  integrationtests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        #        python-version: [3.8, 3.9, 3.10.4]
        python-version: [3.9]

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: corsikasimtelpackage
        run: |
          wget --no-verbose https://syncandshare.desy.de/index.php/s/${{ secrets.CLOUD_SIMTEL }}/download
          mv download ./dev/corsika7.7_simtelarray.tar.gz

      - name: build
        run: |
          cd ./dev
          docker build -t gammasim-tools-dev .

      - name: unittest
        run: |
          cd dev/external
          git clone https://github.com/gammasim/gammasim-tools.git
          cd ..
          docker run -t --rm -v "$(pwd)/external:/workdir/external" gammasim-tools-dev bash -c "$(cat ./entrypoint.sh) && pytest tests/unit_tests/"
